version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: ludusavi-runner
    main: ./cmd/ludusavi-runner
    binary: ludusavi-runner
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/sharkusmanch/ludusavi-runner/pkg/version.Version={{.Version}}
      - -X github.com/sharkusmanch/ludusavi-runner/pkg/version.Commit={{.Commit}}
      - -X github.com/sharkusmanch/ludusavi-runner/pkg/version.Date={{.Date}}

archives:
  - id: default
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - config.example.toml

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

release:
  draft: false
  prerelease: auto
